# fly.toml file generated for still-brook-7124 on 2022-12-15T08:14:35Z

app = "still-brook-7124"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  [build.args]
    NODE_VERSION = "14"
    PHP_VERSION = "8.1"

[env]
  APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  
  APP_URL = "https://tasklist_dep.fly.dev"
  APP_NAME = "TaskList"
  APP_DEBUG = false
  DB_CONNECTION = "pgsql"
  DB_HOST = "db.fvfqszziukvdadhqqzpw.supabase.co"
  DB_PORT = 5432
  DB_DATABASE = "postgres"
  DB_USERNAME = "postgres"


[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
